// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXyS-ZeZVlCEOCjAal2INY7sD6LvLgKUE',
    appId: '1:955568888176:web:e83c8537b2e3a353c617b5',
    messagingSenderId: '955568888176',
    projectId: 'al-sakr',
    authDomain: 'al-sakr.firebaseapp.com',
    databaseURL: 'https://al-sakr-default-rtdb.firebaseio.com',
    storageBucket: 'al-sakr.firebasestorage.app',
    measurementId: 'G-NC66B2GRZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArEsMgTImm-B_5zPbukVqnQYnZnX_xmew',
    appId: '1:955568888176:android:17344da00a97a03fc617b5',
    messagingSenderId: '955568888176',
    projectId: 'al-sakr',
    databaseURL: 'https://al-sakr-default-rtdb.firebaseio.com',
    storageBucket: 'al-sakr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAolsEIhEEkIX1F61-7X28axPv0BvQiegw',
    appId: '1:955568888176:ios:0b4a1b503ef7e298c617b5',
    messagingSenderId: '955568888176',
    projectId: 'al-sakr',
    databaseURL: 'https://al-sakr-default-rtdb.firebaseio.com',
    storageBucket: 'al-sakr.firebasestorage.app',
    iosBundleId: 'com.example.accountingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAolsEIhEEkIX1F61-7X28axPv0BvQiegw',
    appId: '1:955568888176:ios:0b4a1b503ef7e298c617b5',
    messagingSenderId: '955568888176',
    projectId: 'al-sakr',
    databaseURL: 'https://al-sakr-default-rtdb.firebaseio.com',
    storageBucket: 'al-sakr.firebasestorage.app',
    iosBundleId: 'com.example.accountingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXyS-ZeZVlCEOCjAal2INY7sD6LvLgKUE',
    appId: '1:955568888176:web:e406ed5f9a9adfdec617b5',
    messagingSenderId: '955568888176',
    projectId: 'al-sakr',
    authDomain: 'al-sakr.firebaseapp.com',
    databaseURL: 'https://al-sakr-default-rtdb.firebaseio.com',
    storageBucket: 'al-sakr.firebasestorage.app',
    measurementId: 'G-BYVYREL6ZK',
  );
}
